/**
 * AFTER: Rotifer Gene — JSON Validator
 *
 * The same JSON validator, migrated to a Rotifer gene.
 * Generated by: rotifer wrap json-validator
 */

import Ajv from "ajv";

const ajv = new Ajv({ allErrors: true });

interface Input {
  json: string;
  schema: string;
}

interface ValidationError {
  message: string;
  path: string;
}

interface Output {
  valid: boolean;
  errors: ValidationError[];
  parsedSuccessfully: boolean;
}

export async function express(input: Input): Promise<Output> {
  let parsedJson: unknown;
  try {
    parsedJson = JSON.parse(input.json);
  } catch (e) {
    return {
      valid: false,
      errors: [{ message: `Invalid JSON: ${(e as Error).message}`, path: "" }],
      parsedSuccessfully: false,
    };
  }

  let parsedSchema: object;
  try {
    parsedSchema = JSON.parse(input.schema);
  } catch (e) {
    return {
      valid: false,
      errors: [{ message: `Invalid schema: ${(e as Error).message}`, path: "" }],
      parsedSuccessfully: true,
    };
  }

  const validate = ajv.compile(parsedSchema);
  const valid = validate(parsedJson);

  return {
    valid,
    errors: valid
      ? []
      : (validate.errors || []).map((e) => ({
          message: e.message || "unknown error",
          path: e.instancePath || "",
        })),
    parsedSuccessfully: true,
  };
}
