/**
 * AFTER: Rotifer Gene — Text Summarizer
 *
 * The same text summarizer, migrated to a Rotifer gene.
 * Generated by: rotifer wrap text-summarizer
 */

interface Input {
  text: string;
  maxLength?: number;
}

interface Output {
  summary: string;
  originalLength: number;
  summaryLength: number;
  compressionRatio: number;
}

export async function express(input: Input): Promise<Output> {
  const maxLength = input.maxLength ?? 100;
  const sentences = input.text.split(/[.!?]+/).filter((s) => s.trim().length > 0);
  const summary = sentences.slice(0, 3).join(". ").trim();
  const truncated = summary.length > maxLength
    ? summary.slice(0, maxLength) + "..."
    : summary;

  return {
    summary: truncated,
    originalLength: input.text.length,
    summaryLength: truncated.length,
    compressionRatio: +(truncated.length / input.text.length).toFixed(2),
  };
}
