/**
 * AFTER: Rotifer Gene — URL Fetcher
 *
 * The same URL fetcher, migrated to a Rotifer gene.
 * Generated by: rotifer wrap url-fetcher
 */

interface Input {
  url: string;
  timeout?: number;
}

interface Output {
  content: string;
  statusCode: number;
  contentType: string;
  truncated: boolean;
  fetchedAt: string;
}

export async function express(input: Input): Promise<Output> {
  const timeout = input.timeout ?? 5000;
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeout);

  try {
    const response = await fetch(input.url, { signal: controller.signal });
    const text = await response.text();

    return {
      content: text.slice(0, 5000),
      statusCode: response.status,
      contentType: response.headers.get("content-type") || "unknown",
      truncated: text.length > 5000,
      fetchedAt: new Date().toISOString(),
    };
  } finally {
    clearTimeout(timer);
  }
}
